Update build-padavan.yml

diff --git a/.github/workflows/build-padavan.yml b/.github/workflows/build-padavan.yml
--- a/.github/workflows/build-padavan.yml
+++ b/.github/workflows/build-padavan.yml
@@ -41,6 +41,10 @@ jobs:
         TNAME: PSG1218
       run: |
         cd /opt/rt-n56u/trunk
+        if [ ! -f configs/templates/$TNAME.config ] ; then
+        echo "configs/templates/$TNAME.config not found "
+        exit 1
+        fi
         sudo ./build_firmware_modify $TNAME
         sudo mv -f images/*.trx /opt/images/
     - name : Upload packages
